AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Todo lambda function
Globals:
  Function:
    Timeout: 3

Resources:
  TodoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: test-test_tag-tf-sam-lambda-todo-handler
      CodeUri: ./src/todo_handler/
      Handler: main.lambda_handler
      Runtime: python3.8
      PackageType: Zip
      Architectures:
        - x86_64
      Events:
        GetHello:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /todo
            Method: any        
      Environment:
        Variables:
          DYNAMO_TABLE_NAME: "tf_sam_todo_table"
          SQS_URL: "https://sqs.ap-southeast-1.amazonaws.com/983670951732/rf_sam_todo_queue"

  TodoPersistFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: test-test_tag-tf-sam-lambda-todo-persist
      CodeUri: ./src/todo_persist/
      Handler: main.lambda_handler
      Runtime: python3.8
      PackageType: Zip
      Architectures:
        - x86_64
      Environment:
        Variables:
          DYNAMO_TABLE_NAME: "tf_sam_todo_table"
      

Outputs:  
  TodoFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt TodoFunction.Arn
  TodoPersistFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt TodoPersistFunction.Arn